export default [
  {
    value: 'AD',
    Code3: 'AND',
    label: 'Andorra',
    InternationalDialingCode: '376',
  },
  {
    value: 'AE',
    Code3: 'ARE',
    label: 'United Arab Emirates',
    InternationalDialingCode: '971',
  },
  {
    value: 'AF',
    Code3: 'AFG',
    label: 'Afghanistan',
    InternationalDialingCode: '93',
  },
  {
    value: 'AG',
    Code3: 'ATG',
    label: 'Antigua and Barbuda',
    InternationalDialingCode: '1',
  },
  {
    value: 'AI',
    Code3: 'AIA',
    label: 'Anguilla',
    InternationalDialingCode: '1',
  },
  {
    value: 'AL',
    Code3: 'ALB',
    label: 'Albania',
    InternationalDialingCode: '355',
  },
  {
    value: 'AM',
    Code3: 'ARM',
    label: 'Armenia',
    InternationalDialingCode: '374',
  },
  {
    value: 'AN',
    Code3: 'ANT',
    label: 'Netherlands Antilles',
    InternationalDialingCode: '599',
  },
  {
    value: 'AO',
    Code3: 'AGO',
    label: 'Angola',
    InternationalDialingCode: '244',
  },
  {
    value: 'AQ',
    Code3: 'ATA',
    label: 'Antarctica',
    InternationalDialingCode: '672',
  },
  {
    value: 'AR',
    Code3: 'ARG',
    label: 'Argentina',
    InternationalDialingCode: '54',
  },
  {
    value: 'AS',
    Code3: 'ASM',
    label: 'American Samoa',
    InternationalDialingCode: '1',
  },
  {
    value: 'AT',
    Code3: 'AUT',
    label: 'Austria',
    InternationalDialingCode: '43',
  },
  {
    value: 'AU',
    Code3: 'AUS',
    label: 'Australia',
    InternationalDialingCode: '61',
  },
  {
    value: 'AW',
    Code3: 'ABW',
    label: 'Aruba',
    InternationalDialingCode: '297',
  },
  {
    value: 'AX',
    Code3: 'ALA',
    label: 'Åland Islands',
    InternationalDialingCode: '358',
  },
  {
    value: 'AZ',
    Code3: 'AZE',
    label: 'Azerbaijan',
    InternationalDialingCode: '994',
  },
  {
    value: 'BA',
    Code3: 'BIH',
    label: 'Bosnia and Herzegovina',
    InternationalDialingCode: '387',
  },
  {
    value: 'BB',
    Code3: 'BRB',
    label: 'Barbados',
    InternationalDialingCode: '1',
  },
  {
    value: 'BD',
    Code3: 'BGD',
    label: 'Bangladesh',
    InternationalDialingCode: '880',
  },
  {
    value: 'BE',
    Code3: 'BEL',
    label: 'Belgium',
    InternationalDialingCode: '32',
  },
  {
    value: 'BF',
    Code3: 'BFA',
    label: 'Burkina Faso',
    InternationalDialingCode: '226',
  },
  {
    value: 'BG',
    Code3: 'BGR',
    label: 'Bulgaria',
    InternationalDialingCode: '359',
  },
  {
    value: 'BH',
    Code3: 'BHR',
    label: 'Bahrain',
    InternationalDialingCode: '973',
  },
  {
    value: 'BI',
    Code3: 'BDI',
    label: 'Burundi',
    InternationalDialingCode: '257',
  },
  {
    value: 'BJ',
    Code3: 'BEN',
    label: 'Benin',
    InternationalDialingCode: '229',
  },
  {
    value: 'BL',
    Code3: 'BLM',
    label: 'Saint Barthélemy',
    InternationalDialingCode: '590',
  },
  {
    value: 'BM',
    Code3: 'BMU',
    label: 'Bermuda',
    InternationalDialingCode: '1',
  },
  {
    value: 'BN',
    Code3: 'BRN',
    label: 'Brunei Darussalam',
    InternationalDialingCode: '673',
  },
  {
    value: 'BO',
    Code3: 'BOL',
    label: 'Bolivia',
    InternationalDialingCode: '591',
  },
  {
    value: 'BQ',
    Code3: 'BES',
    label: 'Bonaire',
    InternationalDialingCode: '599',
  },
  {
    value: 'BR',
    Code3: 'BRA',
    label: 'Brazil',
    InternationalDialingCode: '55',
  },
  {
    value: 'BS',
    Code3: 'BHS',
    label: 'Bahamas',
    InternationalDialingCode: '1',
  },
  {
    value: 'BT',
    Code3: 'BTN',
    label: 'Bhutan',
    InternationalDialingCode: '975',
  },
  {
    value: 'BV',
    Code3: 'BVT',
    label: 'Bouvet Island',
    InternationalDialingCode: '47',
  },
  {
    value: 'BW',
    Code3: 'BWA',
    label: 'Botswana',
    InternationalDialingCode: '267',
  },
  {
    value: 'BY',
    Code3: 'BLR',
    label: 'Belarus',
    InternationalDialingCode: '375',
  },
  {
    value: 'BZ',
    Code3: 'BLZ',
    label: 'Belize',
    InternationalDialingCode: '501',
  },
  {
    value: 'CA',
    Code3: 'CAN',
    label: 'Canada',
    InternationalDialingCode: '1',
  },
  {
    value: 'CC',
    Code3: 'CCK',
    label: 'Cocos (Keeling) Islands',
    InternationalDialingCode: '672',
  },
  {
    value: 'CD',
    Code3: 'COD',
    label: 'Congo Dem. Rep.',
    InternationalDialingCode: '243',
  },
  {
    value: 'CF',
    Code3: 'CAF',
    label: 'Central African Republic',
    InternationalDialingCode: '236',
  },
  {
    value: 'CG',
    Code3: 'COG',
    label: 'Congo, Rep.',
    InternationalDialingCode: '242',
  },
  {
    value: 'CH',
    Code3: 'CHE',
    label: 'Switzerland',
    InternationalDialingCode: '41',
  },
  {
    value: 'CI',
    Code3: 'CIV',
    label: "Côte d'Ivoire",
    InternationalDialingCode: '225',
  },
  {
    value: 'CK',
    Code3: 'COK',
    label: 'Cook Islands',
    InternationalDialingCode: '682',
  },
  {
    value: 'CL',
    Code3: 'CHL',
    label: 'Chile',
    InternationalDialingCode: '56',
  },
  {
    value: 'CM',
    Code3: 'CMR',
    label: 'Cameroon',
    InternationalDialingCode: '237',
  },
  {
    value: 'CO',
    Code3: 'COL',
    label: 'Colombia',
    InternationalDialingCode: '57',
  },
  {
    value: 'CR',
    Code3: 'CRI',
    label: 'Costa Rica',
    InternationalDialingCode: '506',
  },
  {
    value: 'CU',
    Code3: 'CUB',
    label: 'Cuba',
    InternationalDialingCode: '53',
  },
  {
    value: 'CV',
    Code3: 'CPV',
    label: 'Cape Verde',
    InternationalDialingCode: '238',
  },
  {
    value: 'CW',
    Code3: 'CUW',
    label: 'Curaçao',
    InternationalDialingCode: '599',
  },
  {
    value: 'CX',
    Code3: 'CXR',
    label: 'Christmas Island',
    InternationalDialingCode: '672',
  },
  {
    value: 'CY',
    Code3: 'CYP',
    label: 'Cyprus',
    InternationalDialingCode: '357',
  },
  {
    value: 'CZ',
    Code3: 'CZE',
    label: 'Czech Republic',
    InternationalDialingCode: '420',
  },
  {
    value: 'DE',
    Code3: 'DEU',
    label: 'Germany',
    InternationalDialingCode: '49',
  },
  {
    value: 'DJ',
    Code3: 'DJI',
    label: 'Djibouti',
    InternationalDialingCode: '253',
  },
  {
    value: 'DK',
    Code3: 'DNK',
    label: 'Denmark',
    InternationalDialingCode: '45',
  },
  {
    value: 'DM',
    Code3: 'DMA',
    label: 'Dominica',
    InternationalDialingCode: '1',
  },
  {
    value: 'DO',
    Code3: 'DOM',
    label: 'Dominican Republic',
    InternationalDialingCode: '1',
  },
  {
    value: 'DZ',
    Code3: 'DZA',
    label: 'Algeria',
    InternationalDialingCode: '213',
  },
  {
    value: 'EC',
    Code3: 'ECU',
    label: 'Ecuador',
    InternationalDialingCode: '593',
  },
  {
    value: 'EE',
    Code3: 'EST',
    label: 'Estonia',
    InternationalDialingCode: '372',
  },
  {
    value: 'EG',
    Code3: 'EGY',
    label: 'Egypt',
    InternationalDialingCode: '20',
  },
  {
    value: 'EH',
    Code3: 'ESH',
    label: 'Western Sahara',
    InternationalDialingCode: '212',
  },
  {
    value: 'ER',
    Code3: 'ERI',
    label: 'Eritrea',
    InternationalDialingCode: '291',
  },
  {
    value: 'ES',
    Code3: 'ESP',
    label: 'Spain',
    InternationalDialingCode: '34',
  },
  {
    value: 'ET',
    Code3: 'ETH',
    label: 'Ethiopia',
    InternationalDialingCode: '251',
  },
  {
    value: 'FI',
    Code3: 'FIN',
    label: 'Finland',
    InternationalDialingCode: '358',
  },
  {
    value: 'FJ',
    Code3: 'FJI',
    label: 'Fiji',
    InternationalDialingCode: '679',
  },
  {
    value: 'FK',
    Code3: 'FLK',
    label: 'Falkland Islands (Islas Malvinas)',
    InternationalDialingCode: '500',
  },
  {
    value: 'FM',
    Code3: 'FSM',
    label: 'Federated States of Micronesia',
    InternationalDialingCode: '691',
  },
  {
    value: 'FO',
    Code3: 'FRO',
    label: 'Faroe Islands',
    InternationalDialingCode: '298',
  },
  {
    value: 'FR',
    Code3: 'FRA',
    label: 'France',
    InternationalDialingCode: '33',
  },
  {
    value: 'GA',
    Code3: 'GAB',
    label: 'Gabon',
    InternationalDialingCode: '241',
  },
  {
    value: 'GB',
    Code3: 'GBR',
    label: 'United Kingdom',
    InternationalDialingCode: '44',
  },
  {
    value: 'GD',
    Code3: 'GRD',
    label: 'Grenada',
    InternationalDialingCode: '1',
  },
  {
    value: 'GE',
    Code3: 'GEO',
    label: 'Georgia',
    InternationalDialingCode: '995',
  },
  {
    value: 'GF',
    Code3: 'GUF',
    label: 'French Guiana',
    InternationalDialingCode: '594',
  },
  {
    value: 'GG',
    Code3: 'GGY',
    label: 'Guernsey',
    InternationalDialingCode: '831',
  },
  {
    value: 'GH',
    Code3: 'GHA',
    label: 'Ghana',
    InternationalDialingCode: '233',
  },
  {
    value: 'GI',
    Code3: 'GIB',
    label: 'Gibraltar',
    InternationalDialingCode: '350',
  },
  {
    value: 'GL',
    Code3: 'GRL',
    label: 'Greenland',
    InternationalDialingCode: '299',
  },
  {
    value: 'GM',
    Code3: 'GMB',
    label: 'Gambia',
    InternationalDialingCode: '220',
  },
  {
    value: 'GN',
    Code3: 'GIN',
    label: 'Guinea',
    InternationalDialingCode: '224',
  },
  {
    value: 'GP',
    Code3: 'GLP',
    label: 'Guadeloupe',
    InternationalDialingCode: '590',
  },
  {
    value: 'GQ',
    Code3: 'GNQ',
    label: 'Equatorial Guinea',
    InternationalDialingCode: '240',
  },
  {
    value: 'GR',
    Code3: 'GRC',
    label: 'Greece',
    InternationalDialingCode: '30',
  },
  {
    value: 'GS',
    Code3: 'SGS',
    label: 'South Georgia and the South Sandwich Islands',
    InternationalDialingCode: '500',
  },
  {
    value: 'GT',
    Code3: 'GTM',
    label: 'Guatemala',
    InternationalDialingCode: '502',
  },
  {
    value: 'GU',
    Code3: 'GUM',
    label: 'Guam',
    InternationalDialingCode: '1',
  },
  {
    value: 'GW',
    Code3: 'GNB',
    label: 'Guinea-Bissau',
    InternationalDialingCode: '245',
  },
  {
    value: 'GY',
    Code3: 'GUY',
    label: 'Guyana',
    InternationalDialingCode: '592',
  },
  {
    value: 'HK',
    Code3: 'HKG',
    label: 'Hong Kong',
    InternationalDialingCode: '852',
  },
  {
    value: 'HM',
    Code3: 'HMD',
    label: 'Heard Island and McDonald Islands',
    InternationalDialingCode: '672',
  },
  {
    value: 'HN',
    Code3: 'HND',
    label: 'Honduras',
    InternationalDialingCode: '504',
  },
  {
    value: 'HR',
    Code3: 'HRV',
    label: 'Croatia',
    InternationalDialingCode: '385',
  },
  {
    value: 'HT',
    Code3: 'HTI',
    label: 'Haiti',
    InternationalDialingCode: '509',
  },
  {
    value: 'HU',
    Code3: 'HUN',
    label: 'Hungary',
    InternationalDialingCode: '36',
  },
  {
    value: 'ID',
    Code3: 'IDN',
    label: 'Indonesia',
    InternationalDialingCode: '62',
  },
  {
    value: 'IE',
    Code3: 'IRL',
    label: 'Ireland',
    InternationalDialingCode: '353',
  },
  {
    value: 'IL',
    Code3: 'ISR',
    label: 'Israel',
    InternationalDialingCode: '972',
  },
  {
    value: 'IM',
    Code3: 'IMN',
    label: 'Isle Of Man',
    InternationalDialingCode: '44',
  },
  {
    value: 'IN',
    Code3: 'IND',
    label: 'India',
    InternationalDialingCode: '91',
  },
  {
    value: 'IO',
    Code3: 'IOT',
    label: 'British Indian Ocean Territory',
    InternationalDialingCode: '246',
  },
  {
    value: 'IQ',
    Code3: 'IRQ',
    label: 'Iraq',
    InternationalDialingCode: '964',
  },
  {
    value: 'IR',
    Code3: 'IRN',
    label: 'Iran, Islamic Republic Of',
    InternationalDialingCode: '98',
  },
  {
    value: 'IS',
    Code3: 'ISL',
    label: 'Iceland',
    InternationalDialingCode: '354',
  },
  {
    value: 'IT',
    Code3: 'ITA',
    label: 'Italy',
    InternationalDialingCode: '39',
  },
  {
    value: 'JE',
    Code3: 'JEY',
    label: 'Jersey',
    InternationalDialingCode: '44',
  },
  {
    value: 'JM',
    Code3: 'JAM',
    label: 'Jamaica',
    InternationalDialingCode: '1',
  },
  {
    value: 'JO',
    Code3: 'JOR',
    label: 'Jordan',
    InternationalDialingCode: '962',
  },
  {
    value: 'JP',
    Code3: 'JPN',
    label: 'Japan',
    InternationalDialingCode: '81',
  },
  {
    value: 'KE',
    Code3: 'KEN',
    label: 'Kenya',
    InternationalDialingCode: '254',
  },
  {
    value: 'KG',
    Code3: 'KGZ',
    label: 'Kyrgyzstan',
    InternationalDialingCode: '996',
  },
  {
    value: 'KH',
    Code3: 'KHM',
    label: 'Cambodia',
    InternationalDialingCode: '855',
  },
  {
    value: 'KI',
    Code3: 'KIR',
    label: 'Kiribati',
    InternationalDialingCode: '686',
  },
  {
    value: 'KM',
    Code3: 'COM',
    label: 'Comoros',
    InternationalDialingCode: '269',
  },
  {
    value: 'KN',
    Code3: 'KNA',
    label: 'Saint Kitts and Nevis',
    InternationalDialingCode: '1',
  },
  {
    value: 'KP',
    Code3: 'PRK',
    label: 'North Korea',
    InternationalDialingCode: '850',
  },
  {
    value: 'KR',
    Code3: 'KOR',
    label: 'South Korea',
    InternationalDialingCode: '82',
  },
  {
    value: 'KW',
    Code3: 'KWT',
    label: 'Kuwait',
    InternationalDialingCode: '965',
  },
  {
    value: 'KY',
    Code3: 'CYM',
    label: 'Cayman Islands',
    InternationalDialingCode: '1',
  },
  {
    value: 'KZ',
    Code3: 'KAZ',
    label: 'Kazakhstan',
    InternationalDialingCode: '7',
  },
  {
    value: 'LA',
    Code3: 'LAO',
    label: 'Laos',
    InternationalDialingCode: '856',
  },
  {
    value: 'LB',
    Code3: 'LBN',
    label: 'Lebanon',
    InternationalDialingCode: '961',
  },
  {
    value: 'LC',
    Code3: 'LCA',
    label: 'Saint Lucia',
    InternationalDialingCode: '1',
  },
  {
    value: 'LI',
    Code3: 'LIE',
    label: 'Liechtenstein',
    InternationalDialingCode: '423',
  },
  {
    value: 'LK',
    Code3: 'LKA',
    label: 'Sri Lanka',
    InternationalDialingCode: '94',
  },
  {
    value: 'LR',
    Code3: 'LBR',
    label: 'Liberia',
    InternationalDialingCode: '231',
  },
  {
    value: 'LS',
    Code3: 'LSO',
    label: 'Lesotho',
    InternationalDialingCode: '266',
  },
  {
    value: 'LT',
    Code3: 'LTU',
    label: 'Lithuania',
    InternationalDialingCode: '370',
  },
  {
    value: 'LU',
    Code3: 'LUX',
    label: 'Luxembourg',
    InternationalDialingCode: '352',
  },
  {
    value: 'LV',
    Code3: 'LVA',
    label: 'Latvia',
    InternationalDialingCode: '371',
  },
  {
    value: 'LY',
    Code3: 'LBY',
    label: 'Libya',
    InternationalDialingCode: '218',
  },
  {
    value: 'MA',
    Code3: 'MAR',
    label: 'Morocco',
    InternationalDialingCode: '212',
  },
  {
    value: 'MC',
    Code3: 'MCO',
    label: 'Monaco',
    InternationalDialingCode: '377',
  },
  {
    value: 'MD',
    Code3: 'MDA',
    label: 'Moldova, Republic of',
    InternationalDialingCode: '373',
  },
  {
    value: 'ME',
    Code3: 'MNE',
    label: 'Montenegro',
    InternationalDialingCode: '382',
  },
  {
    value: 'MF',
    Code3: 'MAF',
    label: 'Saint Martin (French part)',
    InternationalDialingCode: '590',
  },
  {
    value: 'MG',
    Code3: 'MDG',
    label: 'Madagascar',
    InternationalDialingCode: '261',
  },
  {
    value: 'MH',
    Code3: 'MHL',
    label: 'Marshall Islands',
    InternationalDialingCode: '692',
  },
  {
    value: 'MK',
    Code3: 'MKD',
    label: 'Macedonia, The Former Yugoslav Republic of',
    InternationalDialingCode: '389',
  },
  {
    value: 'ML',
    Code3: 'MLI',
    label: 'Mali',
    InternationalDialingCode: '223',
  },
  {
    value: 'MM',
    Code3: 'MMR',
    label: 'Myanmar',
    InternationalDialingCode: '95',
  },
  {
    value: 'MN',
    Code3: 'MNG',
    label: 'Mongolia',
    InternationalDialingCode: '976',
  },
  {
    value: 'MO',
    Code3: 'MAC',
    label: 'Macao',
    InternationalDialingCode: '853',
  },
  {
    value: 'MP',
    Code3: 'MNP',
    label: 'Northern Mariana Islands',
    InternationalDialingCode: '1',
  },
  {
    value: 'MQ',
    Code3: 'MTQ',
    label: 'Martinique',
    InternationalDialingCode: '596',
  },
  {
    value: 'MR',
    Code3: 'MRT',
    label: 'Mauritania',
    InternationalDialingCode: '222',
  },
  {
    value: 'MS',
    Code3: 'MSR',
    label: 'Montserrat',
    InternationalDialingCode: '1',
  },
  {
    value: 'MT',
    Code3: 'MLT',
    label: 'Malta',
    InternationalDialingCode: '356',
  },
  {
    value: 'MU',
    Code3: 'MUS',
    label: 'Mauritius',
    InternationalDialingCode: '230',
  },
  {
    value: 'MV',
    Code3: 'MDV',
    label: 'Maldives',
    InternationalDialingCode: '960',
  },
  {
    value: 'MW',
    Code3: 'MWI',
    label: 'Malawi',
    InternationalDialingCode: '265',
  },
  {
    value: 'MX',
    Code3: 'MEX',
    label: 'Mexico',
    InternationalDialingCode: '52',
  },
  {
    value: 'MY',
    Code3: 'MYS',
    label: 'Malaysia',
    InternationalDialingCode: '60',
  },
  {
    value: 'MZ',
    Code3: 'MOZ',
    label: 'Mozambique',
    InternationalDialingCode: '258',
  },
  {
    value: 'NA',
    Code3: 'NAM',
    label: 'Namibia',
    InternationalDialingCode: '264',
  },
  {
    value: 'NC',
    Code3: 'NCL',
    label: 'New Caledonia',
    InternationalDialingCode: '687',
  },
  {
    value: 'NE',
    Code3: 'NER',
    label: 'Niger',
    InternationalDialingCode: '227',
  },
  {
    value: 'NF',
    Code3: 'NFK',
    label: 'Norfolk Island',
    InternationalDialingCode: '672',
  },
  {
    value: 'NG',
    Code3: 'NGA',
    label: 'Nigeria',
    InternationalDialingCode: '234',
  },
  {
    value: 'NI',
    Code3: 'NIC',
    label: 'Nicaragua',
    InternationalDialingCode: '505',
  },
  {
    value: 'NL',
    Code3: 'NLD',
    label: 'Netherlands',
    InternationalDialingCode: '31',
  },
  {
    value: 'NO',
    Code3: 'NOR',
    label: 'Norway',
    InternationalDialingCode: '47',
  },
  {
    value: 'NP',
    Code3: 'NPL',
    label: 'Nepal',
    InternationalDialingCode: '977',
  },
  {
    value: 'NR',
    Code3: 'NRU',
    label: 'Nauru',
    InternationalDialingCode: '674',
  },
  {
    value: 'NU',
    Code3: 'NIU',
    label: 'Niue',
    InternationalDialingCode: '683',
  },
  {
    value: 'NZ',
    Code3: 'NZL',
    label: 'New Zealand',
    InternationalDialingCode: '64',
  },
  {
    value: 'OM',
    Code3: 'OMN',
    label: 'Oman',
    InternationalDialingCode: '968',
  },
  {
    value: 'PA',
    Code3: 'PAN',
    label: 'Panama',
    InternationalDialingCode: '507',
  },
  {
    value: 'PE',
    Code3: 'PER',
    label: 'Peru',
    InternationalDialingCode: '51',
  },
  {
    value: 'PF',
    Code3: 'PYF',
    label: 'French Polynesia',
    InternationalDialingCode: '689',
  },
  {
    value: 'PG',
    Code3: 'PNG',
    label: 'Papua New Guinea',
    InternationalDialingCode: '675',
  },
  {
    value: 'PH',
    Code3: 'PHL',
    label: 'Philippines',
    InternationalDialingCode: '63',
  },
  {
    value: 'PK',
    Code3: 'PAK',
    label: 'Pakistan',
    InternationalDialingCode: '92',
  },
  {
    value: 'PL',
    Code3: 'POL',
    label: 'Poland',
    InternationalDialingCode: '48',
  },
  {
    value: 'PM',
    Code3: 'SPM',
    label: 'Saint-Pierre and Miquelon',
    InternationalDialingCode: '508',
  },
  {
    value: 'PN',
    Code3: 'PCN',
    label: 'Pitcairn',
    InternationalDialingCode: '872',
  },
  {
    value: 'PR',
    Code3: 'PRI',
    label: 'Puerto Rico',
    InternationalDialingCode: '1',
  },
  {
    value: 'PS',
    Code3: 'PSE',
    label: 'Palestine, State of',
    InternationalDialingCode: '970',
  },
  {
    value: 'PT',
    Code3: 'PRT',
    label: 'Portugal',
    InternationalDialingCode: '351',
  },
  {
    value: 'PW',
    Code3: 'PLW',
    label: 'Palau',
    InternationalDialingCode: '680',
  },
  {
    value: 'PY',
    Code3: 'PRY',
    label: 'Paraguay',
    InternationalDialingCode: '595',
  },
  {
    value: 'QA',
    Code3: 'QAT',
    label: 'Qatar',
    InternationalDialingCode: '974',
  },
  {
    value: 'RE',
    Code3: 'REU',
    label: 'Réunion',
    InternationalDialingCode: '262',
  },
  {
    value: 'RO',
    Code3: 'ROU',
    label: 'Romania',
    InternationalDialingCode: '40',
  },
  {
    value: 'RS',
    Code3: 'SRB',
    label: 'Serbia',
    InternationalDialingCode: '381',
  },
  {
    value: 'RU',
    Code3: 'RUS',
    label: 'Russian Federation',
    InternationalDialingCode: '7',
  },
  {
    value: 'RW',
    Code3: 'RWA',
    label: 'Rwanda',
    InternationalDialingCode: '250',
  },
  {
    value: 'SA',
    Code3: 'SAU',
    label: 'Saudi Arabia',
    InternationalDialingCode: '966',
  },
  {
    value: 'SB',
    Code3: 'SLB',
    label: 'Solomon Islands',
    InternationalDialingCode: '667',
  },
  {
    value: 'SC',
    Code3: 'SYC',
    label: 'Seychelles',
    InternationalDialingCode: '248',
  },
  {
    value: 'SD',
    Code3: 'SDN',
    label: 'Sudan',
    InternationalDialingCode: '249',
  },
  {
    value: 'SE',
    Code3: 'SWE',
    label: 'Sweden',
    InternationalDialingCode: '46',
  },
  {
    value: 'SG',
    Code3: 'SGP',
    label: 'Singapore',
    InternationalDialingCode: '65',
  },
  {
    value: 'SH',
    Code3: 'SHN',
    label: 'Saint Helena',
    InternationalDialingCode: '290',
  },
  {
    value: 'SI',
    Code3: 'SVN',
    label: 'Slovenia',
    InternationalDialingCode: '386',
  },
  {
    value: 'SJ',
    Code3: 'SJM',
    label: 'Svalbard and Jan Mayen',
    InternationalDialingCode: '47',
  },
  {
    value: 'SK',
    Code3: 'SVK',
    label: 'Slovakia',
    InternationalDialingCode: '421',
  },
  {
    value: 'SL',
    Code3: 'SLE',
    label: 'Sierra Leone',
    InternationalDialingCode: '232',
  },
  {
    value: 'SM',
    Code3: 'SMR',
    label: 'San Marino',
    InternationalDialingCode: '378',
  },
  {
    value: 'SN',
    Code3: 'SEN',
    label: 'Senegal',
    InternationalDialingCode: '221',
  },
  {
    value: 'SO',
    Code3: 'SOM',
    label: 'Somalia',
    InternationalDialingCode: '252',
  },
  {
    value: 'SR',
    Code3: 'SUR',
    label: 'Suriname',
    InternationalDialingCode: '597',
  },
  {
    value: 'SS',
    Code3: 'SSD',
    label: 'South Sudan',
    InternationalDialingCode: '211',
  },
  {
    value: 'ST',
    Code3: 'STP',
    label: 'São Tomé and Príncipe',
    InternationalDialingCode: '239',
  },
  {
    value: 'SV',
    Code3: 'SLV',
    label: 'El Salvador',
    InternationalDialingCode: '503',
  },
  {
    value: 'SX',
    Code3: 'SXM',
    label: 'Sint Maarten (Dutch part)',
    InternationalDialingCode: '721',
  },
  {
    value: 'SY',
    Code3: 'SYR',
    label: 'Syrian Arab Republic',
    InternationalDialingCode: '963',
  },
  {
    value: 'SZ',
    Code3: 'SWZ',
    label: 'Swaziland',
    InternationalDialingCode: '268',
  },
  {
    value: 'TC',
    Code3: 'TCA',
    label: 'Turks and Caicos Islands',
    InternationalDialingCode: '1',
  },
  {
    value: 'TD',
    Code3: 'TCD',
    label: 'Chad',
    InternationalDialingCode: '235',
  },
  {
    value: 'TF',
    Code3: 'ATF',
    label: 'French Southern Territories',
    InternationalDialingCode: '672',
  },
  {
    value: 'TG',
    Code3: 'TGO',
    label: 'Togo',
    InternationalDialingCode: '228',
  },
  {
    value: 'TH',
    Code3: 'THA',
    label: 'Thailand',
    InternationalDialingCode: '66',
  },
  {
    value: 'TJ',
    Code3: 'TJK',
    label: 'Tajikistan',
    InternationalDialingCode: '992',
  },
  {
    value: 'TK',
    Code3: 'TKL',
    label: 'Tokelau',
    InternationalDialingCode: '690',
  },
  {
    value: 'TL',
    Code3: 'TLS',
    label: 'Timor-Leste',
    InternationalDialingCode: '670',
  },
  {
    value: 'TM',
    Code3: 'TKM',
    label: 'Turkmenistan',
    InternationalDialingCode: '993',
  },
  {
    value: 'TN',
    Code3: 'TUN',
    label: 'Tunisia',
    InternationalDialingCode: '216',
  },
  {
    value: 'TO',
    Code3: 'TON',
    label: 'Tonga',
    InternationalDialingCode: '676',
  },
  {
    value: 'TR',
    Code3: 'TUR',
    label: 'Turkey',
    InternationalDialingCode: '90',
  },
  {
    value: 'TT',
    Code3: 'TTO',
    label: 'Trinidad and Tobago',
    InternationalDialingCode: '1',
  },
  {
    value: 'TV',
    Code3: 'TUV',
    label: 'Tuvalu',
    InternationalDialingCode: '688',
  },
  {
    value: 'TW',
    Code3: 'TWN',
    label: 'Taiwan (Republic of China)',
    InternationalDialingCode: '886',
  },
  {
    value: 'TZ',
    Code3: 'TZA',
    label: 'Tanzania',
    InternationalDialingCode: '255',
  },
  {
    value: 'UA',
    Code3: 'UKR',
    label: 'Ukraine',
    InternationalDialingCode: '380',
  },
  {
    value: 'UG',
    Code3: 'UGA',
    label: 'Uganda',
    InternationalDialingCode: '256',
  },
  {
    value: 'UM',
    Code3: 'UMI',
    label: 'United States Minor Outlying Islands',
    InternationalDialingCode: '1',
  },
  {
    value: 'US',
    Code3: 'USA',
    label: 'United States',
    InternationalDialingCode: '1',
  },
  {
    value: 'UY',
    Code3: 'URY',
    label: 'Uruguay',
    InternationalDialingCode: '598',
  },
  {
    value: 'UZ',
    Code3: 'UZB',
    label: 'Uzbekistan',
    InternationalDialingCode: '998',
  },
  {
    value: 'VA',
    Code3: 'VAT',
    label: 'Vatican',
    InternationalDialingCode: '39',
  },
  {
    value: 'VC',
    Code3: 'VCT',
    label: 'Saint Vincent and the Grenadines',
    InternationalDialingCode: '1',
  },
  {
    value: 'VE',
    Code3: 'VEN',
    label: 'Venezuela',
    InternationalDialingCode: '58',
  },
  {
    value: 'VG',
    Code3: 'VGB',
    label: 'British Virgin Islands',
    InternationalDialingCode: '1',
  },
  {
    value: 'VI',
    Code3: 'VIR',
    label: 'U.S. Virgin Islands',
    InternationalDialingCode: '1',
  },
  {
    value: 'VN',
    Code3: 'VNM',
    label: 'Viet Nam',
    InternationalDialingCode: '84',
  },
  {
    value: 'VU',
    Code3: 'VUT',
    label: 'Vanuatu',
    InternationalDialingCode: '678',
  },
  {
    value: 'WF',
    Code3: 'WLF',
    label: 'Wallis and Futuna',
    InternationalDialingCode: '681',
  },
  {
    value: 'WS',
    Code3: 'WSM',
    label: 'Samoa',
    InternationalDialingCode: '685',
  },
  {
    value: 'YE',
    Code3: 'YEM',
    label: 'Yemen',
    InternationalDialingCode: '967',
  },
  {
    value: 'YT',
    Code3: 'MYT',
    label: 'Mayotte',
    InternationalDialingCode: '269',
  },
  {
    value: 'ZA',
    Code3: 'ZAF',
    label: 'South Africa',
    InternationalDialingCode: '27',
  },
  {
    value: 'ZM',
    Code3: 'ZMB',
    label: 'Zambia',
    InternationalDialingCode: '260',
  },
  {
    value: 'ZW',
    Code3: 'ZWE',
    label: 'Zimbabwe',
    InternationalDialingCode: '263',
  },
];
